"""
MQL5 export.

This writes scaffolding: inputs matching your spec, the detector translated as
faithfully as the language allows, and clearly marked stubs where you must
supply broker-specific handling. It is not a finished EA and does not pretend
to be. Anything that claims to turn a statistical spec into a live expert
advisor without human work is skipping the part where money is lost.
"""

from __future__ import annotations

from datetime import datetime, timezone

from .spec import Spec

_ORDER_BLOCK_DETECT = r"""
//--- Order block detection -------------------------------------------------
// Returns true and fills zoneLow/zoneHigh when a zone confirmed on bar `shift`.
bool DetectOrderBlock(int shift, double &zoneLow, double &zoneHigh, int &bias)
{
   double atrBuf[];
   if(CopyBuffer(gAtrHandle, 0, shift+InpDisplacementBars, 2, atrBuf) <= 0) return false;
   double refAtr = atrBuf[0];
   if(refAtr <= 0) return false;

   int start = shift + InpDisplacementBars - 1;
   double move = iClose(_Symbol, InpTimeframe, shift) - iOpen(_Symbol, InpTimeframe, start);
   double size = MathAbs(move) / refAtr;
   if(size < InpDisplacementATR) return false;
   bool bull = move > 0;

   if(InpRequireSwingBreak)
   {
      int hi = iHighest(_Symbol, InpTimeframe, MODE_HIGH, InpSwingLookback, start+1);
      int lo = iLowest(_Symbol, InpTimeframe, MODE_LOW,  InpSwingLookback, start+1);
      if(bull  && !(iHigh(_Symbol,InpTimeframe,shift) > iHigh(_Symbol,InpTimeframe,hi))) return false;
      if(!bull && !(iLow(_Symbol,InpTimeframe,shift)  < iLow(_Symbol,InpTimeframe,lo)))  return false;
   }

   // last opposite-close candle before the move
   int found = -1;
   for(int j = start+1; j <= start + InpSwingLookback + 5; j++)
   {
      double o = iOpen(_Symbol, InpTimeframe, j);
      double c = iClose(_Symbol, InpTimeframe, j);
      if((bull && c < o) || (!bull && c > o)) { found = j; break; }
   }
   if(found < 0) return false;

   double o = iOpen(_Symbol, InpTimeframe, found);
   double c = iClose(_Symbol, InpTimeframe, found);
   if(InpZoneFromWick)
   { zoneLow = iLow(_Symbol,InpTimeframe,found); zoneHigh = iHigh(_Symbol,InpTimeframe,found); }
   else
   { zoneLow = MathMin(o,c); zoneHigh = MathMax(o,c); }

   bias = bull ? 1 : -1;
   return zoneHigh > zoneLow;
}
"""

_GENERIC_DETECT = r"""
//--- Detector stub ---------------------------------------------------------
// TODO: the study used detector "{detector}", which has no MQL5 translation
// in this exporter yet. Implement it here to match the Python definition in
// edgelab/detectors.py exactly, or the live behaviour will not match the study.
bool DetectZone(int shift, double &zoneLow, double &zoneHigh, int &bias)
{{
   return false;
}}
"""


def export(spec: Spec, summary: dict | None = None) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    s = spec.scoring
    zp = spec.zone.resolved()
    tf = _mql_timeframe(spec.timeframe)

    stats_block = ""
    if summary:
        stats_block = f"""//   Sample:      n={summary.get('n')}, win rate {_pct(summary.get('rate'))}
//   95% CI:      {_pct(summary.get('ci_low'))} to {_pct(summary.get('ci_high'))}
//   Baseline:    {_pct(summary.get('baseline_rate'))}
//   Mean R:      {_num(summary.get('mean_r'))}
//   Ambiguous:   {_pct(summary.get('ambiguous'))} of events"""

    if spec.zone.detector == "order_block":
        detect = _ORDER_BLOCK_DETECT
        detect_call = "DetectOrderBlock"
    else:
        detect = _GENERIC_DETECT.format(detector=spec.zone.detector)
        detect_call = "DetectZone"

    filters = "\n".join(
        f"//     {f}" for f in spec.filters) or "//     (none)"

    return f"""//+------------------------------------------------------------------+
//|  {spec.name[:60]}
//|  Generated by Edge Lab, {now}
//|  Spec fingerprint: {spec.fingerprint()}
//+------------------------------------------------------------------+
//
//  THIS IS SCAFFOLDING, NOT A FINISHED EA.
//
//  What is here:   the detector, zone test, and stop/target arithmetic
//                  transcribed from the study spec.
//  What is NOT:    position sizing, spread and slippage handling, news and
//                  session guards, partial fills, weekend gaps, magic-number
//                  hygiene, and any prop-firm drawdown rules. Those are marked
//                  TODO and they are where live results diverge from studies.
//
//  The study measured zone reactions with a limit fill at the zone edge and no
//  costs. A CFD spread on {spec.symbol or 'this instrument'} will consume part
//  of that edge. Re-test in the MT5 tester with real spread before trusting it.
//
{stats_block}
//
//  Filters the study applied — these are NOT implemented below:
{filters}
//+------------------------------------------------------------------+
#property strict

input ENUM_TIMEFRAMES InpTimeframe        = {tf};
input double          InpDisplacementATR  = {zp.get('displacement_atr', 1.5)};
input int             InpDisplacementBars = {zp.get('displacement_bars', 1)};
input bool            InpRequireSwingBreak= {str(zp.get('require_swing_break', True)).lower()};
input int             InpSwingLookback    = {zp.get('swing_lookback', 10)};
input bool            InpZoneFromWick     = {str(zp.get('zone_from', 'body') == 'wick').lower()};
input int             InpMaxAgeBars       = {zp.get('max_age_bars', 500)};
input bool            InpFirstTestOnly    = {str(spec.trigger.first_test_only).lower()};
input double          InpStopValue        = {s.stop.value};
input double          InpTargetValue      = {s.target.value};
input int             InpMaxHoldingMinutes= {s.max_holding_bars};
input double          InpRiskPercent      = 0.5;   // TODO: set for your account
input int             InpAtrPeriod        = 14;
input int             InpMagic            = 20260906;

int gAtrHandle = INVALID_HANDLE;

// Stop mode from the study: {s.stop.mode}
// Target mode from the study: {s.target.mode}
// Entry from the study: {s.entry}
// Direction: {spec.direction}

int OnInit()
{{
   gAtrHandle = iATR(_Symbol, InpTimeframe, InpAtrPeriod);
   if(gAtrHandle == INVALID_HANDLE) return INIT_FAILED;
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason) {{ IndicatorRelease(gAtrHandle); }}
{detect}
//--- Stop and target from the zone, matching the study ---------------------
void LevelsFromZone(int bias, double zoneLow, double zoneHigh, double atr,
                    double &entry, double &stop, double &target)
{{
   entry = (bias == 1) ? zoneHigh : zoneLow;
   double height = zoneHigh - zoneLow;
{_levels_body(s)}
}}

void OnTick()
{{
   static datetime lastBar = 0;
   datetime t = iTime(_Symbol, InpTimeframe, 0);
   if(t == lastBar) return;            // act once per closed bar
   lastBar = t;

   // TODO: session filter, spread guard, existing-position check,
   //       daily drawdown check against your prop firm's rules.

   double zoneLow, zoneHigh, entry, stop, target;
   int bias;
   if(!{detect_call}(1, zoneLow, zoneHigh, bias)) return;
{_direction_guard(spec)}
   double atrBuf[];
   if(CopyBuffer(gAtrHandle, 0, 1, 1, atrBuf) <= 0) return;
   LevelsFromZone(bias, zoneLow, zoneHigh, atrBuf[0], entry, stop, target);

   // TODO: place a pending limit at `entry` with `stop` and `target`,
   //       sized from InpRiskPercent and the distance entry-stop.
   //       Expire it after InpMaxAgeBars bars if unfilled.
   //       Close any fill after InpMaxHoldingMinutes minutes.
   PrintFormat("zone %.2f-%.2f bias %d entry %.2f stop %.2f target %.2f",
               zoneLow, zoneHigh, bias, entry, stop, target);
}}
//+------------------------------------------------------------------+
"""


def _levels_body(s) -> str:
    if s.stop.mode == "zone_far_edge":
        stop = ("   double far = (bias == 1) ? zoneLow : zoneHigh;\n"
                "   stop = far - (InpStopValue - 1.0) * height * bias;")
    elif s.stop.mode == "atr":
        stop = "   stop = entry - bias * InpStopValue * atr;"
    else:
        stop = "   stop = entry - bias * InpStopValue * _Point;"

    if s.target.mode == "r_multiple":
        tgt = ("   double risk = (entry - stop) * bias;\n"
               "   target = entry + bias * InpTargetValue * risk;")
    elif s.target.mode == "atr":
        tgt = "   target = entry + bias * InpTargetValue * atr;"
    elif s.target.mode == "none":
        tgt = "   target = 0.0;   // study used a time exit only"
    else:
        tgt = "   target = entry + bias * InpTargetValue * _Point;"
    return stop + "\n" + tgt


def _direction_guard(spec) -> str:
    if spec.direction == "long":
        return "   if(bias != 1) return;\n"
    if spec.direction == "short":
        return "   if(bias != -1) return;\n"
    return ""


def _mql_timeframe(tf: str) -> str:
    import pandas as pd
    mins = int(pd.Timedelta(tf).total_seconds() // 60)
    table = {1: "PERIOD_M1", 5: "PERIOD_M5", 15: "PERIOD_M15", 30: "PERIOD_M30",
             60: "PERIOD_H1", 240: "PERIOD_H4", 1440: "PERIOD_D1"}
    return table.get(mins, "PERIOD_M5")


def _pct(v):
    return f"{v:.1%}" if isinstance(v, (int, float)) and v == v else "n/a"


def _num(v):
    return f"{v:.3f}" if isinstance(v, (int, float)) and v == v else "n/a"
